Add the Array Node, which enables Array UDFs.
TileDB-Inc/TileDB-Cloud-Py pull request #323
Opened 2022-08-04 21:33 UTC by thetorpedodog

This adds and tests the Array node, so that users can actually start
doing interesting TileDB-specific things with their UDFs by passing in
their TileDB arrays as values.

This also streamlines the process of default-handling with `NOTHING`,
by making a central place to strip `NOTHING`s out of kwarg dictionaries.

2022-08-09 13:58 UTC, antalakas approved these changes

2022-08-09 14:00 UTC, antalakas requested changes
Probably we need to address this https://github.com/TileDB-Inc/TileDB-Cloud-Py/pull/324#discussion_r939183623 comment

2022-08-09 15:03 UTC, thetorpedodog commented
Re @Shelnutt2’s comment on the other change:

> This should be `DelayedArrayUDF` to match the existing API. `DelayedArray` also has special meaning in the ecosystem which is why we used the specific name of `DelayedArrayUDF`.

I think the use of `DelayedArray` here is correct; the object you get back from `DelayedArray` is something you can *pass into* a UDF to pass the array into your UDF.

Separately, I’ve added a `DelayedArrayUDF` function which combines `Delayed` and `DelayedArray` together into one, and matches up with the existing `DelayedArrayUDF` API:

```python
arr_udf = DelayedArrayUDF(
    some_func,
    "tiledb://array/path",
    **array_kwargs,
    **delayed_kwargs,
)(other, inputs)
# Will eventually call some_func(array_contents, other, inputs)

# equivalent to

arr = DelayedArray("tiledb://array/path", **array_kwargs)
arr_udf = Delayed(some_func, **delayed_kwargs)(arr, other, inputs)
# Also will eventually call some_func(array_contents, other, inputs)
```

2022-08-09 16:16 UTC, antalakas reviewed
I am good with this, but I'd like an approve from @Shelnutt2 also

2024-05-17 18:48 UTC, JohnMoutafis commented
Closing this as it is not relevant anymore.

2024-05-17 18:48 UTC, closed without merging