`invite_to_organization`: fix `InvitationOrganizationJoinEmail` ctor call
TileDB-Inc/TileDB-Cloud-Py pull request #637
Opened 2024-09-04 17:52 UTC by ryan-williams

[sc-54346]

2024-09-04 19:34 UTC, ryan-williams commented
Looks like the `autobuild` GHA has been failing off and on lately, including on `main` currently. Anyone have context?

2024-09-04 21:09 UTC, sgillies requested changes
Looks correct to me @ryan-williams ! Can you add a line about `actions` to the docstring and a simple test? I don't think we need much more than a new `test_organization.py` and a test that calls `invite_to_organization()`, mocking tiledb.cloud.client, so that we can be sure that we've got it wired properly and that it stays that way.

For the docstring, it's okay to be vague, like we are for the other parameters. Eventually it could be nice to include a enumeration of acceptable values (here 
https://github.com/TileDB-Inc/TileDB-Cloud-API-Spec/blob/3783c171eb780c47c7c5890a3616870c2bb9e061/openapi-v1.yaml#L330, I think), but we don't need to figure out the best way to do that now.

2024-09-04 21:29 UTC, thetorpedodog commented
> Looks like the `autobuild` GHA has been failing off and on lately, including on `main` currently. Anyone have context?

This looks like we’re trying to write things to the same backend path in multiple tests and it’s stepping on each other. We (the main maintainers of this package, not necessarily you) should make sure we set up per-run unique paths for our tests.

2024-09-10 14:12 UTC, sgillies approved these changes

2024-09-10 14:12 UTC, merged