Register DAG
TileDB-Inc/TileDB-Cloud-Py pull request #692
Opened 2024-12-30 20:51 UTC by spencerseale

Adds functionality to register a `DAG` instance:

```python
from tiledb.cloud.taskgraphs.registration import register

graph = DAG(name="dag-testing-tg-deps-2")

stagea = graph.submit(func=lambda x: x)
stageb = graph.submit(func=lambda x: x, args=(stagea,))
stagec = graph.submit(func=lambda x: x, args=(stagea,))
staged = graph.submit(func=lambda x: x, args=(stageb, stagec,))

register(
    graph=graph,
    namespace="spencerseale"
)
```

I need to update type hint in tiledb.cloud.taskgraphs.registration.register to `graph: Union[tgbuilder, DAG]`. So I then add the import to that module `from tiledb.cloud.dag.dag import DAG`. But it's interesting, when I go to do that using my editable install and then run:

`python -m src.tiledb.cloud.dag.dag`

 I get: 
```
(tiledb-cloud-py-py39) spencerseale 12:27 PM $ TileDB-Cloud-Py python -m src.tiledb.cloud.dag.dag

Traceback (most recent call last):
  File "/Users/spencerseale/miniconda3/envs/tiledb-cloud-py-py39/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/spencerseale/miniconda3/envs/tiledb-cloud-py-py39/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/spencerseale/tiledb_apis/TileDB-Cloud-Py/src/tiledb/cloud/__init__.py", line 3, in <module>
    from . import array
  File "/Users/spencerseale/tiledb_apis/TileDB-Cloud-Py/src/tiledb/cloud/array.py", line 7, in <module>
    from . import client
  File "/Users/spencerseale/tiledb_apis/TileDB-Cloud-Py/src/tiledb/cloud/client.py", line 13, in <module>
    import tiledb.cloud._common.api_v2.models as models_v2
ImportError: cannot import name 'cloud' from 'tiledb' (/Users/spencerseale/miniconda3/envs/tiledb-cloud-py-py39/lib/python3.9/site-packages/tiledb/__init__.py)
```

I get the same stack trace when I update the module `tiledb.cloud.taskgraphs.registration` to import anything. I think this is the way we have cloud-py wired up and how the Py system path is getting created. Switching to `poetry` or something similar would fix the dev experience a lot so the current dev library is installed into the system path as a Python library to simulate how cloud-py will execute as an installed library.

@sgillies any ideas on this?

2025-01-15 23:59 UTC, sgillies reviewed
@spencerseale I've got a suggestion and a question inline.

2025-01-15 23:59 UTC, sgillies commented on src/tiledb/cloud/dag/dag.py
> +        override_name: Optional[str] = None,
Let's use just `name` here like we do in other methods.

2025-01-15 23:59 UTC, sgillies commented on src/tiledb/cloud/dag/dag.py
> +            A.meta["dataset_type"] = "registered_task_graph"
It would be nice if the registration endpoint could take metadata, then this would be more atomic.

2025-01-15 23:59 UTC, sgillies commented on src/tiledb/cloud/dag/dag.py
> +            namespace=self.namespace,
At first, I was wondering where all the new private methods were coming from, and then I realized you had copied them from the taskgraph module, and that they are called by the JSON serializer. I think this is an okay way to go. Could you look into another approach, to make sure that we're not missing out on a chance to do this with less code?

It occurs to me that `dag.compute()` uses our task graph builder to produce JSON that is sent to the server to be executed. Isn't this the same JSON that we would use when registering? Could your new `register()` method run `_build_batch_taskgraph()`, for example, to produce the JSON?

If this is a dumb or not workable idea, I will gladly drop it.

2025-01-16 00:41 UTC, sgillies commented
@spencerseale if registration.py imports dag.py and dag.py imports registration.py we have a circular import, no? Let's avoid doing that, especially if only to have perfect type hints. I think it's okay to relax the typing for `registration.register()` and use `graph: Any` for now.

But if we do want better type hints without a circular import... `registration.register()` can actually accept any argument that has a `_tdb_to_json()` method. So, we could create an abstract base class with that method and register `DAG` with the ABC, or we could use Python structural typing.

2025-01-16 01:21 UTC, sgillies commented
@spencerseale about test failures: tiledb versions 0.33.1 and 0.33.2 broke the `CloudArray` interface. If you see errors like `AttributeError: 'SparseArrayImpl' object has no attribute 'apply'` (for example) in our autobuild jobs, they aren't caused by your changes.

2025-01-23 22:41 UTC, sgillies commented on src/tiledb/cloud/dag/dag.py
> +            namespace=self.namespace,
@spencerseale I have a better idea, one that will make new modules and new interfaces unnecessary for now. Instead of importing `tiledb.cloud.taskgraphs.registration` (which tangles our modules together) and calling `registration.register()`, copy the body of `registration.register()` into `Dag.register()`.

A little bit of code duplication, it's only two copies, doesn't bother me at all.

2025-02-14 22:09 UTC, sgillies requested changes
@spencerseale looking good! I have a couple recommendations.

2025-02-14 22:09 UTC, sgillies commented on tests/test_dag.py
> +    graph = dag.DAG(name="dag-test-fixture", namespace=default_user().username)
@spencerseale I believe we will need a globally unique name for the DAG since the new test might be run at the same time for two different Python versions.

2025-02-14 22:09 UTC, sgillies commented on tests/test_dag.py
> +    registered_name2 = dag_fixture.register(name="override-name")
We'll need a globally unique name for registration here, too.

2025-02-14 22:09 UTC, sgillies commented on tests/test_dag.py
> +        dag_fixture.register()
Finally, should we ensure that the registered DAGs are deleted?

2025-02-15 00:11 UTC, sgillies commented
@spencerseale I think this will need to be rebased onto main as well (the wheel test, for example).

2025-02-17 15:46 UTC, spencerseale commented on tests/test_dag.py
> +    graph = dag.DAG(name="dag-test-fixture", namespace=default_user().username)
Good point and i'll try and be more aware of that in the future!

2025-02-21 18:56 UTC, spencerseale commented on tests/test_dag.py
> +        dag_fixture.register()
The registration is mocked, so nothing is actually being registered. The api model is assumed tested elsewhere, so this unittest just tests the wrapper around the `rest_api.RegisteredTaskGraphsApi`

2025-02-24 19:53 UTC, sgillies approved these changes
Great @spencerseale !

2025-02-24 19:53 UTC, merged